### ISSUE TITLE
Mismatch between actionlib_tutorials wiki and this repository

### ISSUE THREAD

**Issue by scpeters** [ros/common_tutorials#13]
I just noticed there's some mismatch between the wiki and this repository. I'm willing to help clean it up if I get some feedback on how it should be fixed.
- The [actionlib_tutorials page](http://wiki.ros.org/actionlib_tutorials) says to create a catkin package called `learning_actionlib`, while this repository has a package called `actionlib_tutorials`.
- The first two beginner tutorials ([Fibonacci c++ server](http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionServer%28ExecuteCallbackMethod%29)
  and [Fibonacci c++ client](http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionClient)) use the `learning_actionlib` package name.
- The two python beginner tutorials use the `actionlib_tutorials` package name. Also, those python scripts are not contained in this git repository.

Should the tutorial recommend to the user how to recreate the contents of the `actionlib_tutorials` package in this repository?

**Comment by scpeters** [comment]
forgot some tutorial links:
- [python Fibonacci server](http://wiki.ros.org/actionlib_tutorials/Tutorials/Writing%20a%20Simple%20Action%20Server%20using%20the%20Execute%20Callback%20%28Python%29)
- [python Fibonacci client](http://wiki.ros.org/actionlib_tutorials/Tutorials/Writing%20a%20Simple%20Action%20Client%20%28Python%29)

**Comment by wjwwood** [comment]
My guess is that someone changed the name of the package that the user creates so that it doesn't interfere with this package which can be installed from `apt-get` and the Python tutorial never got updated. The Python tutorial is also out of date because it still has the `import roslib; roslib.load_manifest('actionlib_tutorials')` line at the top of the Python script, which is only needed for `rosbuild` and not for `catkin`. I'd suggest updating the Python tutorial to be in line with the introduction tutorial and the C++ parts of the tutorial.

**Comment by scpeters** [comment]
Do you suggest that we keep different package names between the wiki and this repository? I was hoping to delete one copy of the code from the wiki and include it from here instead, but that isn't possible if they are using different package names.

We can also keep it as is (with two copies of the code) if that's preferred.

**Comment by wjwwood** [comment]
No, the idea is that the package the user creates is not hosted anywhere and that it is identical, except in name, to the one here on github. The one here on github is the "answer". But I think that we could go back to using just the `actionlib_tutorials` name and drop the `learning_actionlib` stuff. I'm not sure who added that in the first place, and I'm only guessing at their motives for doing so.

**Comment by 130s** [comment]
I just stumbled upon this ticket where I think I'm partly responsible for the issue discussed. I tracked back the history and figured out:

- Both C++ and Python tutorials started off using `learning_actionlib`, instead of `actionlib_tutorials`.
- When I added catkin version of Python tutorials, I [replaced](http://wiki.ros.org/action/info/actionlib_tutorials/Tutorials/Writing%20a%20Simple%20Action%20Server%20using%20the%20Execute%20Callback%20%28Python%29?action=diff&rev2=20&rev1=19) `learning_actionlib` with `actionlib_tutorials`.
- The actionlib_tutorials package, which is now hosted on [this repo](https://github.com/ros/common_tutorials), has always been named `actionlib_tutorials` (eg. [init commit on this github repo](https://github.com/ros/common_tutorials/commit/95614df05bb500353eba5112c0458809f802bf3d#diff-7c2cd6ce2bc1323e9aa243163c987cc4)) (except for short term it was renamed (between [this](https://github.com/ros/common_tutorials/commit/d0fe2a206aae6fd45b08ac60881cdc83539e2c60#diff-7c2cd6ce2bc1323e9aa243163c987cc4) and [this](https://github.com/ros/common_tutorials/commit/4f503b04d90f2ae94b1e8cb32feed945fbd4c5f3#diff-7c2cd6ce2bc1323e9aa243163c987cc4))).

> the idea is that the package the user creates is not hosted anywhere and that it is identical, except in name, to the one here on github. The one here on github is the "answer". But I think that we could go back to using just the actionlib_tutorials name and drop the learning_actionlib stuff.

+1, and I've just added all the necessary changes on the tutorials. Now hopefully there's no `learning_actionlib` stuff on the tutorials.

> the Python tutorial never got updated. The Python tutorial is also out of date because it still has the import roslib; roslib.load_manifest('actionlib_tutorials') line at the top of the Python script, which is only needed for rosbuild and not for catkin. 

This should also be fixed now.

**Comment by scpeters** [comment]
I still see a few instances of `learning_actionlib` in the following wiki pages:

* http://wiki.ros.org/actionlib_tutorials
* http://wiki.ros.org/actionlib_tutorials/Tutorials/RunningServerAndClient
* http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionServer%28GoalCallbackMethod%29
* http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionClient%28Threaded%29
* http://wiki.ros.org/actionlib_tutorials/Tutorials/RunningServerAndClientWithNodes

**Comment by 130s** [comment]
@scpeters Thanks for the check, I'm working on it now.

**Comment by 130s** [comment]
Hopefully done.

**Comment by scpeters** [comment]
thanks!
